# Generated by Django 3.0.5 on 2020-04-20 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameplay', '0003_auto_20170606_1314'),
        ('gameplay', '0003_auto_20170805_1700'),
    ]

    operations = [
    ]
